# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mus - Computational Science
description: 'Computational Science'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.musbenziane.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  musbenziane
html_dir:  '' # ltl ( default ) "rtl", ltl
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /blog/:title:output_ext
paginate: 5
paginate_path: "/blog/page:num/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

comments:
  provider               : 'disqus' # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : 'mus-benziane' # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : 'pink'
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# google map key
google_map_key           : 'AIzaSyDz2w7HUaWudHwd7AWQpCL48Qs050WOn9s' # false (default),

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


##########################################################################
################# seo ####################################################
##########################################################################
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
og_image                 : '/images/profile.jpg' # Open Graph/Twitter default site image
header:
  - image                 : '/images/profile.jpg'

###########################################################################
########### Home Card #####################################################
###########################################################################

home_style:  'background-image' # background-image (default), "background-color", "particles-bg", "video-bg"

first_name: Mus
last_name: Benziane
email:
phone:
address: France, Grenoble.
freelance_hire: true
professions:
  - a Geophysicist
  - a new Researcher
  - Looking for a PhD studenship

author_description: "<strong>Hello, I’m Mus</strong>, I'm currently a student at the University of Grenoble Alpes in France, doing a research Masters in Geophysics. I'm interested in computational geophysics and high performance computing.
Currently, I am actively looking for a PhD position for next year."
social_link:
  - name: download
    text: "Download CV"
    link: "#"
  - name: github
    text: "Come over!"
    link: "https://github.com/musbenziane"
  - name:
    text: ""
    link: "#"
  - name:
    text: ""
    link: "#"

######### Our Services ######################

our_services:
  - name: "Forward Modeling"
    icon: "la la-angle-double-right"
    description: "Forward Modeling."

  - name: "Inverse Problems"
    icon: "la la-angle-double-left"
    description: "Inverse Problems."

  - name: "Numerical Methods"
    icon: "la la-code"
    description: "Numerical Methods."

  - name: "High Performance Computing"
    icon: "la la-server"
    description: "High Performance Computing."

  - name: "Computational Geophysics"
    icon: "la la-globe"
    description: "Computational Geophysics."

  - name: "Programming"
    icon: "la la-code-fork"
    description: "Programming."


####### Pricing Tables ##########
pricing_table:
  - name: "BASIC"
    icon: "la la-tachometer"
    price: "22"
    lines: >-
        <li>Web Development</li>
        <li>Advetising</li>
        <li>Game Development</li>
        <li class="disable">Music Writing</li>
        <li class="disable">Photography <strong>new</strong></li>
    url: "#"

  - name: "PRO"
    icon: "la la-rocket"
    price: "48"
    lines: >-
          <li>Web Development</li>
          <li>Advetising</li>
          <li>Game Development</li>
          <li>Music Writing</li>
          <li>Photography <strong>new</strong></li>
    url: "#"

########### Fun Facts ###############
fun_facts:
  - name: "47 Albumes Listened"
    icon: "la la-headphones"
  - name: "15 Awards Won"
    icon: "la la-trophy"
  - name: "54 Projects Completed"
    icon: "la la-lightbulb-o"
  - name: "10 Countries Visited"
    icon: "la la-flag-o"
  - name: "50+ Books Readed"
    icon: "la la-book"
  - name: "100 000 Lines of Code"
    icon: "la la-code"
  - name: "49 Satisfied Customers"
    icon: "la la-smile-o"
  - name: "1250 km Cycled"
    icon: "la la-bicycle"



############ Clients ##########
clients:
  - image: "images/clients/client_1.png"
    name: ""
    url: "#"
  - image: "images/clients/client_2.png"
    name: ""
    url: "#"
  - image: "images/clients/client_3.png"
    name: ""
    url: "#"
  - image: "images/clients/client_4.png"
    name: ""
    url: "#"
  - image: "images/clients/client_1.png"
    name: ""
    url: "#"
  - image: "images/clients/client_2.png"
    name: ""
    url: "#"
  - image: "images/clients/client_3.png"
    name: ""
    url: "#"
  - image: "images/clients/client_4.png"
    name: ""
    url: "#"


#################################################
############ resume-card ########################
#################################################
############ My Experience ###################

my_experience:
  - name: "Research Intern"
    date: May-2021-July-2021 <span>|</span> ISTerre.
    description: "
Seismic Elastic Modeling in Land Setting with Complex Near Surface, using the SEAM ARID model and a SEM 2D Solver."
  - name: "Geophysicist, Engineer"
    date: "2017-2020 <span>|</span> GeoEXplo dz."
    description: "&#8226; Acquisition, processing, interpretation and reporting of near surface Geophysical data.
    <br>  &#8226; Mount Sopris Instruments (MSI) well logging equipement sales, training and technical support
     <br> &#8226; Communications, website & social media pages administration."


################ My Education #############
my_education:
  - name: "Grenoble University"
    date: 2020-2022 <span>|</span> Grenoble
    description: "Master's Degree (Research oriented), Geophysics and Seismology"
  - name: "Boumerdes University"
    date: "2014-2016 <span>|</span> Boumerdes"
    description: "Master's Degree, Petroleum Geophysics"

personal_skills:
  - name: 'Fortran'

  - name: 'OpenMP'
    percentage: '75'

  - name: 'Matlab & Python'
    percentage: '65'

  - name: 'Numerical Methods'
    percentage: '85'

professional_skills:
  - name: 'WordPress'
    percentage: '90'

  - name: 'PHP / MYSQL'
    percentage: '65'

  - name: 'HTML / CSS / JS'
    percentage: '95'

  - name: 'Photoshop'
    percentage: '85'


#############################################
################## works-card ###############
#############################################
portfolio_categories:
  - name: "Photo"
    slug: "photo"
  - name: "Video"
    slug: "video"
  - name: "Music"
    slug: "music"
  - name: "Design"
    slug: "design"

portfolios:
  - category: 'photo'
    image: 'images/works/work1.jpg'
    name: 'Motorcycle Helmet'
    type: image

  - category: 'video'
    image: 'images/works/work2.jpg'
    name: 'Minimalism Shapes'
    video: 'https://vimeo.com/97102654'
    type: video

  - category: 'design'
    image: 'images/works/work3.jpg'
    name: 'Mobile Application'
    type: image

  - category: 'photo'
    image: 'images/works/work4.jpg'
    name: 'Motorcycle Helmet'
    type: image

  - category: 'photo'
    image: 'images/works/work1.jpg'
    name: 'Motorcycle Helmet'
    type: image

  - category: 'photo'
    image: 'images/works/work2.jpg'
    name: 'Motorcycle Helmet'
    type: image

  - category: 'photo'
    image: 'images/works/work3.jpg'
    name: 'Motorcycle Helmet'
    type: image

  - category: 'photo'
    image: 'images/works/work1.jpg'
    name: 'Motorcycle Helmet'
    type: image
